# Env
env:
  global:
  - secure: "Bpk0MKl7UBsIlNd0LrbDzElBZxS3OQJaetXlQHbNus6YZiVLC60/bo9Gu9StrBKcdrGifqzpgdETBuCUNl9ncODGba5bj4i/n6EbrXUaSWagwi6wnNjMJW3BzeUqaJabrpb6FVg9oKqdI7cfRelasJhVjpcVPnMULRxGnKtnMaY="
# Language
language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
# Scripts
before_script:
- composer selfupdate --quiet
- composer require 'phpunit/phpunit=4.2.*' --prefer-source
- composer install -n --prefer-source --dev
script:
- |
  echo;
  echo "Running unit tests";
  lib/vendor/phpunit/phpunit/phpunit --bootstrap tests/phpunit_bootstrap.php --color tests/
- |
  echo; echo "Running php lint"; /bin/bash -c "
    if ! find lib -name \*.php -not -path 'lib/vendor/*' -exec php -l {} \; > /tmp/errors 2>&1; then
      grep -v \"No syntax errors detected in\" /tmp/errors;
      exit 99;
    fi
  "
